name: camouflage
main: me.arboriginal.camouflage.Camouflage
version: 1.0
author: arboriginal
website: http://dev.bukkit.org/server-mods/camouflage/
dev-url: https://github.com/arboriginal/Camouflage
description: Mobs and players can camouflage themselves.
depend: [Spout]

commands:
    camouflage-reload:
        description: Camouflage Configuration Reload (ccr)
        permission: camouflage.reload
        usage: /camouflage-reload
        aliases: [ccr]

permissions:
    camouflage.*:
        description: Give access to all Camouflage functions
        children:
            camouflage.reload: true
            camouflage.use: true
    
    camouflage.reload:
        description: Allow to reload the plugin configuration
        default: op
        
    camouflage.use:
        description: Allow to use camouflage by sneaking
        default: true
